### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by sunta3iouxos** [olaolsso/pixiple#6]
I think that introduction of a done tag should help out alot.
In detail, there are photos that are marked as possible identical due to huge colour uniformity (?), such are photos of the sea or big green fields. But the details in those are different like people, weather, etc.
creating a log entry that will be set for the user as false positive, would eliminate those photos in a new scan.

Hope it makes sense and is easy to be implemented

By the way the excellent software.

**Comment by saolaolsson** [comment]
Thank you for the suggestion. I can see the use for such a feature, but until Pixiple starts caching previous results, I'd rather keep things simple and not save data to disk.
